"""
Morning Market Briefing — Nicolas Roth
v5: Macro section generated by Claude as text (not separate HTML block)
    + max_tokens raised to 4000 to avoid truncation
    + Summary table built in Python from price data (not delegated to Claude)
"""

import os
import json
import math
import smtplib
import datetime
import yfinance as yf
import requests
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from anthropic import Anthropic

# ── Config ────────────────────────────────────────────────────────────────────

WATCHLIST = {
    "TPG":       {"name": "TPG Inc.",                      "exchange": "NASDAQ"},
    "ECO":       {"name": "Okeanis Eco Tankers Corp.",     "exchange": "NYSE"},
    "ALPHA.AT":  {"name": "Alpha Bank S.A.",               "exchange": "Athens (ATHEX)"},
    "TRMD":      {"name": "TORM plc",                      "exchange": "Nasdaq US"},
    "FRO":       {"name": "Frontline plc",                 "exchange": "NYSE"},
    "DOV.MI":    {"name": "doValue S.p.A.",                "exchange": "Borsa Italiana"},
    "INTRUM.ST": {"name": "Intrum AB",                     "exchange": "Nasdaq Stockholm"},
    "TEN":       {"name": "Tsakos Energy Navigation Ltd.", "exchange": "NYSE"},
}

RECIPIENT_EMAIL = "Nicolas.w.roth@gmail.com"
SENDER_EMAIL    = os.environ["GMAIL_ADDRESS"]
GMAIL_APP_PASS  = os.environ["GMAIL_APP_PASSWORD"]
ANTHROPIC_KEY   = os.environ["ANTHROPIC_API_KEY"]
PERPLEXITY_KEY  = os.environ["PERPLEXITY_API_KEY"]

# ── 1. Fetch Macro Data ────────────────────────────────────────────────────────

def fetch_macro() -> dict:
    macro = {}
    instruments = [
        ("ES=F",     "S&P 500 Futures"),
        ("NQ=F",     "Nasdaq 100 Futures"),
        ("BZ=F",     "Brent Crude (USD/bbl)"),
        ("CL=F",     "WTI Crude (USD/bbl)"),
        ("^TNX",     "US 10Y Yield (%)"),
        ("EURUSD=X", "EUR/USD"),
        ("SEKUSD=X", "SEK/USD"),
    ]
    for ticker, label in instruments:
        try:
            hist = yf.Ticker(ticker).history(period="5d")
            hist = hist[hist["Close"].notna()]
            if len(hist) < 2:
                macro[label] = {"error": "no data"}
                continue
            last = round(float(hist["Close"].iloc[-1]), 4)
            prev = round(float(hist["Close"].iloc[-2]), 4)
            chg  = round((last - prev) / prev * 100, 2)
            macro[label] = {"last": last, "chg_pct": chg}
        except Exception as e:
            macro[label] = {"error": str(e)}
    return macro


def fetch_macro_news() -> str:
    url     = "https://api.perplexity.ai/chat/completions"
    headers = {"Authorization": f"Bearer {PERPLEXITY_KEY}", "Content-Type": "application/json"}
    prompt  = (
        "List the 5 most important macro/market headlines from the last 12 hours for equity investors. "
        "Focus on: Fed/ECB statements, geopolitical events, commodity moves, major data releases, systemic events. "
        "Format: bullet points, one sentence each, source and time if available."
    )
    payload = {"model": "sonar", "messages": [{"role": "user", "content": prompt}]}
    try:
        r = requests.post(url, headers=headers, json=payload, timeout=30)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]
    except Exception as e:
        return f"Macro news unavailable: {e}"


# ── 2. Fetch Stock Prices ──────────────────────────────────────────────────────

def fetch_prices(tickers: list) -> dict:
    data = {}
    for ticker in tickers:
        try:
            stock = yf.Ticker(ticker)
            hist = None
            for period in ["5d", "1mo"]:
                h = stock.history(period=period)
                h = h[h["Close"].notna()]
                if len(h) >= 2:
                    hist = h
                    break
            if hist is None or len(hist) < 2:
                data[ticker] = {"error": "no data"}
                continue

            close_today = round(float(hist["Close"].iloc[-1]), 2)
            close_prev  = round(float(hist["Close"].iloc[-2]), 2)
            pct_change  = round((close_today - close_prev) / close_prev * 100, 2)
            vol         = float(hist["Volume"].iloc[-1])
            avg_vol     = float(hist["Volume"].mean())
            volume      = int(vol)     if not math.isnan(vol)     else 0
            avg_volume  = int(avg_vol) if not math.isnan(avg_vol) else 0
            vol_ratio   = round(volume / avg_volume, 2) if avg_volume > 0 else 0

            info = stock.fast_info
            try:
                week52_high   = round(float(info.year_high), 2)
                week52_low    = round(float(info.year_low),  2)
                pct_from_high = round((close_today - week52_high) / week52_high * 100, 1)
            except Exception:
                week52_high = week52_low = pct_from_high = None

            try:
                currency = info.currency
            except Exception:
                currency = "USD"

            data[ticker] = {
                "name":           WATCHLIST[ticker]["name"],
                "close":          close_today,
                "prev_close":     close_prev,
                "currency":       currency,
                "pct_change":     pct_change,
                "volume":         volume,
                "avg_volume":     avg_volume,
                "vol_ratio":      vol_ratio,
                "week52_high":    week52_high,
                "week52_low":     week52_low,
                "pct_from_high":  pct_from_high,
            }
        except Exception as e:
            data[ticker] = {"error": str(e), "name": WATCHLIST[ticker]["name"]}
    return data


# ── 3. Fetch Stock News ────────────────────────────────────────────────────────

def fetch_news_perplexity(ticker: str, company_name: str) -> str:
    url     = "https://api.perplexity.ai/chat/completions"
    headers = {"Authorization": f"Bearer {PERPLEXITY_KEY}", "Content-Type": "application/json"}
    prompt  = (
        f"List the most important news from the last 24 hours about {company_name} ({ticker}). "
        f"Focus on: earnings, analyst calls, M&A, regulatory events, management changes. "
        f"One sentence per item with source. If nothing material: 'No material news in last 24h'."
    )
    payload = {"model": "sonar", "messages": [{"role": "user", "content": prompt}]}
    try:
        r = requests.post(url, headers=headers, json=payload, timeout=30)
        r.raise_for_status()
        return r.json()["choices"][0]["message"]["content"]
    except Exception as e:
        return f"News unavailable: {e}"


# ── 4. Synthesize Narratives with Claude (no table) ───────────────────────────

def synthesize_narratives(macro: dict, macro_news: str, prices: dict, news: dict) -> str:
    """Claude writes ONLY the narrative sections. Table is built in Python."""
    client = Anthropic(api_key=ANTHROPIC_KEY)
    today  = datetime.date.today().strftime("%A %d %B %Y")

    system_prompt = (
        "You are a senior equity analyst writing a pre-market briefing for a portfolio manager. "
        "Write in institutional register: dense, declarative, no marketing language. "
        "Display prices in their native currency (field 'currency' in data). "
        "Output ONLY the narrative sections below — do NOT write a summary table, I will add it separately.\n\n"
        "SECTIONS TO WRITE (use these exact HTML tags):\n"
        "<h3>MACRO OVERNIGHT</h3>\n"
        "3-4 sentences synthesising futures, oil, rates, key headlines. "
        "Connect macro to watchlist explicitly: Brent/WTI → ECO/TRMD/FRO/TEN; "
        "EUR/USD → DOV/INTRUM; 10Y yield → ALPHA. Flag moves >1% with ⚠️.\n\n"
        "<h3>ALERTS</h3>\n"
        "Flag stock moves >2% or material news. Omit section entirely if none.\n\n"
        "<h3>PRIVATE EQUITY</h3>\n"
        "TPG: one paragraph (price → volume → news → implication).\n\n"
        "<h3>GREEK BANKS</h3>\n"
        "Alpha Bank: one paragraph.\n\n"
        "<h3>TANKER SHIPPING</h3>\n"
        "ECO, TRMD, FRO, TEN: one paragraph each.\n\n"
        "<h3>CREDIT / NPL SERVICERS</h3>\n"
        "doValue, Intrum: one paragraph each.\n\n"
        "Be concise. 3-4 sentences per paragraph maximum. No table. Clean HTML only."
    )

    user_prompt = f"""Date: {today}

MACRO DATA: {json.dumps(macro)}

MACRO NEWS:
{macro_news}

STOCK DATA: {json.dumps(prices)}

STOCK NEWS:
{"".join([f"[{t}] {n}\n" for t, n in news.items()])}"""

    response = client.messages.create(
        model      = "claude-sonnet-4-6",
        max_tokens = 3000,
        system     = system_prompt,
        messages   = [{"role": "user", "content": user_prompt}],
    )
    return response.content[0].text.replace("```html", "").replace("```", "").strip()


# ── 5. Build Summary Table in Python ──────────────────────────────────────────

def build_summary_table(prices: dict) -> str:
    """Builds the summary table directly from price data — never truncated."""
    def arrow(chg):
        if chg is None: return "—"
        return f"{'▲' if chg >= 0 else '▼'}{abs(chg)}%"

    def color(chg):
        if chg is None: return "#888"
        return "#1a7a3f" if chg >= 0 else "#c0392b"

    rows = ""
    for ticker, d in prices.items():
        if "error" in d:
            rows += f"""<tr>
              <td><b>{ticker}</b></td>
              <td>{d.get('name','—')}</td>
              <td colspan="6" style="color:#888">Data unavailable</td>
            </tr>"""
            continue

        cur   = d.get("currency", "")
        close = f"{cur} {d['close']}" if d.get("close") else "—"
        chg   = d.get("pct_change")
        vr    = f"{d['vol_ratio']}x" if d.get("vol_ratio") else "—"
        h52   = f"{cur} {d['week52_high']}" if d.get("week52_high") else "—"
        pfh   = f"{d['pct_from_high']}%" if d.get("pct_from_high") is not None else "—"
        chg_s = arrow(chg)
        chg_c = color(chg)

        rows += f"""<tr>
          <td><b>{ticker}</b></td>
          <td style="font-size:11px">{d.get('name','—')}</td>
          <td>{close}</td>
          <td style="color:{chg_c};font-weight:600">{chg_s}</td>
          <td>{vr}</td>
          <td>{h52}</td>
          <td>{pfh}</td>
        </tr>"""

    return f"""
<table width="100%" cellpadding="0" cellspacing="0"
       style="border-collapse:collapse;font-size:12px;margin-top:8px">
  <tr style="background:#003d4d;color:#fff">
    <th style="padding:7px 9px;text-align:left">Ticker</th>
    <th style="padding:7px 9px;text-align:left">Name</th>
    <th style="padding:7px 9px;text-align:left">Last</th>
    <th style="padding:7px 9px;text-align:left">Chg%</th>
    <th style="padding:7px 9px;text-align:left">Vol/Avg</th>
    <th style="padding:7px 9px;text-align:left">52W High</th>
    <th style="padding:7px 9px;text-align:left">% from High</th>
  </tr>
  {rows}
</table>"""


# ── 6. Build Macro Bar ────────────────────────────────────────────────────────

def build_macro_bar(macro: dict) -> str:
    def cell(label, key):
        d = macro.get(key, {})
        if "error" in d or not d:
            val = "N/A"
            chg_html = ""
        else:
            val  = d["last"]
            chg  = d["chg_pct"]
            col  = "#7ee8a2" if chg >= 0 else "#ff9999"
            arr  = "▲" if chg >= 0 else "▼"
            chg_html = f" <span style='color:{col}'>{arr}{abs(chg)}%</span>"
        return (f"<td style='padding:6px 12px;color:#d0e8ee;font-size:11px;"
                f"white-space:nowrap;border-right:1px solid #024055'>"
                f"{label}<br><b style='font-size:12.5px;color:#fff'>{val}</b>{chg_html}</td>")

    cells = (
        cell("S&amp;P Fut",  "S&P 500 Futures") +
        cell("NQ Fut",       "Nasdaq 100 Futures") +
        cell("Brent",        "Brent Crude (USD/bbl)") +
        cell("WTI",          "WTI Crude (USD/bbl)") +
        cell("US 10Y",       "US 10Y Yield (%)") +
        cell("EUR/USD",      "EUR/USD") +
        cell("SEK/USD",      "SEK/USD")
    )
    return (f"<table width='100%' cellpadding='0' cellspacing='0' "
            f"style='background:#012e3a'><tr>{cells}</tr></table>")


# ── 7. Build & Send Email ──────────────────────────────────────────────────────

def build_email_html(narratives: str, table_html: str, macro: dict) -> str:
    today     = datetime.date.today().strftime("%A %d %B %Y")
    macro_bar = build_macro_bar(macro)

    return f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"></head>
<body style="margin:0;padding:0;background:#f4f4f4;
             font-family:'Helvetica Neue',Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0">
<tr><td align="center" style="padding:30px 0">
<table width="700" cellpadding="0" cellspacing="0"
       style="background:#fff;border-radius:6px;
              box-shadow:0 2px 8px rgba(0,0,0,0.08)">

  <tr><td style="background:#003d4d;padding:20px 30px;border-radius:6px 6px 0 0">
    <div style="color:#fff;font-size:17px;font-weight:600">Morning Market Briefing</div>
    <div style="color:#a8c8d0;font-size:11px;margin-top:4px">
      {today} · 08:00 CET · TPG · ECO · ALPHA · TRMD · FRO · DOV · INTRUM · TEN
    </div>
  </td></tr>

  <tr><td>{macro_bar}</td></tr>

  <tr><td style="padding:24px 30px;color:#2c2c2c;font-size:13.5px;line-height:1.65">
    {narratives}
    <br>
    <p style="font-size:11px;text-transform:uppercase;letter-spacing:0.9px;
              color:#003d4d;border-bottom:1px solid #e0e0e0;padding-bottom:5px;
              margin:20px 0 10px"><b>SUMMARY TABLE</b></p>
    {table_html}
  </td></tr>

  <tr><td style="background:#f4f4f4;padding:12px 30px;font-size:11px;
                 color:#999;text-align:center;border-radius:0 0 6px 6px">
    Generated by Claude · Prices: Yahoo Finance · News: Perplexity · Internal use only
  </td></tr>

</table>
</td></tr></table>
</body></html>"""


def send_email(html_body: str):
    today   = datetime.date.today().strftime("%d %b %Y")
    subject = f"Morning Briefing · 8 titres · {today}"
    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = SENDER_EMAIL
    msg["To"]      = RECIPIENT_EMAIL
    msg.attach(MIMEText(html_body, "html"))
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(SENDER_EMAIL, GMAIL_APP_PASS)
        server.sendmail(SENDER_EMAIL, RECIPIENT_EMAIL, msg.as_string())
    print(f"✅ Briefing sent to {RECIPIENT_EMAIL}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    tickers = list(WATCHLIST.keys())

    print("🌍 Fetching macro data...")
    macro = fetch_macro()

    print("📰 Fetching macro news...")
    macro_news = fetch_macro_news()

    print("📊 Fetching stock prices...")
    prices = fetch_prices(tickers)

    print("📰 Fetching stock news...")
    news = {t: fetch_news_perplexity(t, WATCHLIST[t]["name"]) for t in tickers}

    print("🤖 Synthesizing narratives with Claude...")
    narratives = synthesize_narratives(macro, macro_news, prices, news)

    print("📊 Building summary table...")
    table_html = build_summary_table(prices)

    print("📧 Building & sending email...")
    html = build_email_html(narratives, table_html, macro)
    send_email(html)


if __name__ == "__main__":
    main()
